//
//  This file was auto-generated by Macaw tools 0.9.7-SNAPSHOT version built on Fri, 13 Apr 2018 08:12:31 +0530 
//
package io.zolontech.services.ed.impl;

import java.lang.Override;

public class Collegescorecard implements com.cfx.service.api.Service, io.zolontech.services.ed.Collegescorecard {
  @Override
  public void initialize(com.cfx.service.api.config.Configuration config) throws com.cfx.service.api.ServiceException {
  }

  @Override
  public void start(com.cfx.service.api.StartContext startContext) throws com.cfx.service.api.ServiceException {
  }

  @Override
  public void stop(com.cfx.service.api.StopContext stopContext) throws com.cfx.service.api.ServiceException {
  }

  @Override
  public io.zolontech.services.ed.SearchSchoolsResponse searchSchools(io.zolontech.services.ed.SearchSchoolsRequest request) {
    // TODO: Auto-generated code;
    return null;
  }

  @Override
  public io.zolontech.services.ed.GetStudentResponse getStudent(io.zolontech.services.ed.GetStudentRequest request) {
    // TODO: Auto-generated code;
    return null;
  }

  @Override
  public io.zolontech.services.ed.AddReviewOrCommentResponse addReviewOrComment(io.zolontech.services.ed.AddReviewOrCommentRequest request) {
    // TODO: Auto-generated code;
    return null;
  }
}
